# web port
server:
  port: 8088
  # no web
  #spring.main.web-environment=false


xxl:
  job:
    ### xxl-job, access token
    accessToken:
    ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
      #XxlJobTemplate相关新增
      username: admin
      password: 123456
    executor:
      ### xxl-job executor appname
      appname: xxl-job-executor-sample
      ### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address:
      ### xxl-job executor server-info
      ip:
      port: 9999
      ### xxl-job executor log-path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job executor log-retention-days
      logretentiondays: 30
spring:
  datasource:
    url: jdbc:mysql://192.168.64.3:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    data-username: root
    data-password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
